services:
  energy404:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energy404_container
    platform: linux/amd64
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    environment:
      - PYTHONBUFFERED=1
    command: sleep infinity